services:
  superkuma:
    image: ronaldodavi/superkuma:2
    # To build the image locally instead of pulling it, comment out `image:`
    # above and uncomment the next line:
    # build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
